title: "Shajan Jacob"
description: "Engineer | Maker | Programmer | Photographer"
avatar: "https://shajanjacob.com/shajan-jacob.jpg"
baseurl: "https://shajanjacob.com"

social:
  email: shajan@gmail.com
  facebook: shajanjp 
  github: shajanjp 
  instagram: shajanjp 
  linkedin: shajanjp 
  pinterest: shajanjp 
  skype: shajanjp 
  twitter: shajanjp 
  youtube: shajanjp 
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  googleplus: # anything in your profile username that comes after plus.google.com/
